USE [master]
GO
/****** Object:  Database [NotesDB]    Script Date: 2021-01-09 20:21:46 ******/
CREATE DATABASE [NotesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NotesDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NotesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NotesDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NotesDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [NotesDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NotesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NotesDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NotesDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NotesDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NotesDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NotesDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [NotesDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NotesDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NotesDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NotesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NotesDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NotesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NotesDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NotesDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NotesDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NotesDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NotesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NotesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NotesDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NotesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NotesDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NotesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NotesDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NotesDB] SET RECOVERY FULL 
GO
ALTER DATABASE [NotesDB] SET  MULTI_USER 
GO
ALTER DATABASE [NotesDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NotesDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NotesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NotesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NotesDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NotesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'NotesDB', N'ON'
GO
ALTER DATABASE [NotesDB] SET QUERY_STORE = OFF
GO
USE [NotesDB]
GO
/****** Object:  Table [dbo].[Note]    Script Date: 2021-01-09 20:21:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Note](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Description] [varchar](200) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdateDate] [datetime] NULL,
 CONSTRAINT [PK__Note__3214EC07226E5ABA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Note__737584F665F4D215] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [NotesDB] SET  READ_WRITE 
GO
